"""Add url column to Url table

Revision ID: 588e856eb17d
Revises: 
Create Date: 2024-04-18 15:52:18.070379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588e856eb17d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=164), nullable=True))
        batch_op.alter_column('encoded',
               existing_type=sa.VARCHAR(length=164),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.drop_index('ix_url_decoded')
        batch_op.create_index(batch_op.f('ix_url_url'), ['url'], unique=False)
        batch_op.drop_column('decoded')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decoded', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_url_url'))
        batch_op.create_index('ix_url_decoded', ['decoded'], unique=False)
        batch_op.alter_column('encoded',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=164),
               existing_nullable=True)
        batch_op.drop_column('url')

    # ### end Alembic commands ###
